use pokedex;
select max(total), min(total), max(hp),min(hp),max(ataque),min(ataque),max(defesa),min(defesa),max(ataque_especial),min(ataque_especial),max(defesa_especial),min(defesa_especial),max(velocidade),min(velocidade),max(taxa_captura),min(taxa_captura) from pokemon;
select count(DISTINCT cor) from pokemon;
select avg(peso_kg) from pokemon;
select sum(altura_m) from pokemon;
select count(*) from pokemon;
select avg(altura_m) from pokemon;
select std(hp) from pokemon;
select count(tipo2) from pokemon;
select count(DISTINCT tipo1) from pokemon;
select sum(peso_kg) from pokemon;
select count(lendario)from pokemon group by lendario; 
select count(*), count(DISTINCT cor) from pokemon ORDER BY COR DESC;
select avg(peso_kg), avg(altura_m) from pokemon ORDER BY peso_kg, altura_m desc ;
select avg(taxa_captura), cor from pokemon group by cor; 
select tipo1,avg(taxa_captura) as captura from pokemon group by tipo1 having captura >100;
select avg(total),nome from pokemon where lendario = 0 group by cor having avg(total) <400; 
select max(total),geracao from pokemon group by geracao; 
select count(lendario),geracao from pokemon where lendario =1 group by geracao;
select count(tipo1), count(tipo2), avg(taxa_captura),geracao from pokemon group by geracao ;
select  count(cor),geracao from pokemon where lendario=1 group by geracao;
